name: python
on:
  push:
    paths:
      - .github/workflows/python.yml
      - lib/*.py
      - t/*.py

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        ls
        pytest t/tests.py
    - name: Test command line help
      run: |
        python lib/hash_sequence.py --help
    - name: Test command line sequence
      run: |
        if [ $(python lib/hash_sequence.py -i ACGT) = '46054055969511637' ]; then
          echo 'correct'
        else
          exit 1 
        fi
    - name: Test command line md5
      run: |
        if [ $(python lib/hash_sequence.py -m f1f8f4bf413b16ad135722aa4591043e) = '46054055969511637' ]; then
          echo 'correct'
        else
          exit 1 
        fi
    - name: Test command line list
      run: |
        if [ $(python lib/hash_sequence.py -l t/seqs.txt | tr '\n' ',') = '46054055969511637,68447323523890455,' ]; then
          echo 'correct'
        else
          exit 1 
        fi
    - name: Test command line output file
      run: |
        if [ $(python lib/hash_sequence.py -l t/seqs.txt -o tmp.txt) = '' ] && [ -f tmp.txt ]; then
          echo 'correct'
        else
          exit 1
        fi
